package p000a.p001a.p002a.p003a.p004a.p005a;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/* JADX INFO: renamed from: a.a.a.a.a.a.a */
/* JADX INFO: loaded from: classes.dex */
public final class C0001a {

    /* JADX INFO: renamed from: a */
    public static final Set<String> f0a = new HashSet(Arrays.asList("OneTrustBannerShownToUser", "OT_IAB_DEFAULT_AVL", "FIRST_TIME_CONSENT_LOG", "OT_CL_DEFAULT_PAYLOAD", "OT_CL_DEFAULT_TRANSACTION_VALUES", "OTT_USER_CONSENT_LOCATION", "OT_DATA_DOWNLOADED_GEO_LOCATION", "OT_CONSENTED_LOCATION", "OTT_CONSENT_STATUS", "OTT_USER_CONSENT_STATUS", "OTT_DEFAULT_USER", "OTT_LAST_GIVEN_CONSENT", "OTT_LAST_RE_CONSENT_DATE", "OTT_PROFILE_SYNC_PROFILE_STRING", "OTT_PROFILE_SYNC_PROFILE_AUTH", "OTT_PROFILE_TENANT_ID", "OTT_PROFILE_SYNC_GROUP_ID", "OTT_PROFILE_CONSENT_RECEIPT", "OTT_PROFILE_ALL_PURPOSES_UPDATED_AFTER_SYNC", "OT_ProfileSyncETag", "OTT_DATA_SUBJECT_IDENTIFIER", "OTT_CREATE_CONSENT_PROFILE_STRING", "OT_IAB_ACTIVE_VENDORLIST", "OT_IAB_TCStr_Created", "OT_IAB_TCStr_LastUpdated", "OT_IAB_TC_STR_CREATED_IN_MILLISECONDS", "OT_IAB_TC_STR_LAST_UPDATED_IN_MILLISECONDS", "INTERACTION_TYPE", "OT_GOOGLE_ACTIVE_VENDOR_LIST", "OT_GENERAL_VENDORS", "OTT_IAB_CONSENTABLE_PURPOSES", "OT_INTERNAL_SDK_STATUS_MAP", "OTT_DATA_SUBJECT_IDENTIFIER_TYPE", "OT_ALL_CONSENTED_GROUPS", "OT_HAS_GROUP_CONFIG_CHANGED", "OT_PROFILE_SYNC_IAB_CONSENT_EXPIRED", "OT_SDK_API_FETCH_TIMESTAMP"));
}
